[package]
name = "connectivity-dbus"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
zbus.workspace = true

connectivity-app = { path = "../connectivity-app" }
connectivity-config = { path = "../connectivity-config" }
connectivity-domain = { path = "../connectivity-domain" }
