[package]
name = "connectivity-backend-bluez"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
tracing.workspace = true
zbus.workspace = true

connectivity-backend = { path = "../connectivity-backend" }
connectivity-domain = { path = "../connectivity-domain" }
