[package]
name = "connectivity-app"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

connectivity-backend = { path = "../connectivity-backend" }
connectivity-domain = { path = "../connectivity-domain" }
connectivity-events = { path = "../connectivity-events" }
