[package]
name = "connectivityd"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

connectivity-app = { path = "../../crates/connectivity-app" }
connectivity-backend-bluez = { path = "../../crates/connectivity-backend-bluez" }
connectivity-backend-nmrs = { path = "../../crates/connectivity-backend-nmrs" }
connectivity-config = { path = "../../crates/connectivity-config" }
connectivity-dbus = { path ="../../crates/connectivity-dbus" }
connectivity-events = { path = "../../crates/connectivity-events" }
connectivity-grpc = { path = "../../crates/connectivity-grpc" }
connectivity-http = { path = "../../crates/connectivity-http" }
