[package]
name = "connectivity-http"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
tokio.workspace = true

connectivity-app = { path = "../connectivity-app" }
