[package]
name = "connectivity-backend-nmrs"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
tracing.workspace = true
nmrs.workspace = true
uuid.workspace = true
tokio.workspace = true

connectivity-backend = { path = "../connectivity-backend" }
connectivity-domain = { path = "../connectivity-domain" }
